In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('fake_job_postings.csv')
df1.head()

job_id                                      title            location  \
0       1                           Marketing Intern    US, NY, New York   
1       2  Customer Service - Cloud Video Production      NZ, , Auckland   
2       3    Commissioning Machinery Assistant (CMA)       US, IA, Wever   
3       4          Account Executive - Washington DC  US, DC, Washington   
4       5                        Bill Review Manager  US, FL, Fort Worth   

  department salary_range                                    company_profile  \
0  Marketing          NaN  We're Food52, and we've created a groundbreaki...   
1    Success          NaN  90 Seconds, the worlds Cloud Video Production ...   
2        NaN          NaN  Valor Services provides Workforce Solutions th...   
3      Sales          NaN  Our passion for improving quality of life thro...   
4        NaN          NaN  SpotSource Solutions LLC is a Global Human Cap...   

                                         description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Rese...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        requirements  \
0  Experience with content management systems a m...   
1  What we expect from you:Your key responsibilit...   
2  Implement pre-commissioning and commissioning ...   
3  EDUCATION: Bachelor’s or Master’s in GIS, busi...   
4  QUALIFICATIONS:RN license in the State of Texa...   

                                            benefits  telecommuting  \
0                                                NaN              0   
1  What you will get from usThrough being part of...              0   
2                                                NaN              0   
3  Our culture is anything but corporate—we have ...              0   
4                              Full Benefits Offered              0   

   has_company_logo  has_questions employment_type required_experience  \
0                 1              0           Other          Internship   
1                 1              0       Full-time      Not Applicable   
2                 1              0             NaN                 NaN   
3                 1              0       Full-time    Mid-Senior level   
4                 1              1       Full-time    Mid-Senior level   

  required_education                   industry              function  \
0                NaN                        NaN             Marketing   
1                NaN  Marketing and Advertising      Customer Service   
2                NaN                        NaN                   NaN   
3  Bachelor's Degree          Computer Software                 Sales   
4  Bachelor's Degree     Hospital & Health Care  Health Care Provider   

   fraudulent  
0           0  
1           0  
2           0  
3           0  
4           0

In [3]:
df1.shape

(17880, 18)

In [4]:
df=df1[['description','requirements','fraudulent']]
df.head()

description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Rese...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        requirements  fraudulent  
0  Experience with content management systems a m...           0  
1  What we expect from you:Your key responsibilit...           0  
2  Implement pre-commissioning and commissioning ...           0  
3  EDUCATION: Bachelor’s or Master’s in GIS, busi...           0  
4  QUALIFICATIONS:RN license in the State of Texa...           0

In [5]:
###Drop Nan Values
df=df.dropna()

In [6]:
df.shape

(15185, 3)

In [7]:
## Get the Independent Features

X=df.drop('fraudulent',axis=1)

In [8]:
## Get the Dependent features
y=df['fraudulent']

In [9]:
y.value_counts()

0    14473
1      712
Name: fraudulent, dtype: int64

In [10]:
import tensorflow as tf
tf.__version__

'2.9.2'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [12]:
voc_size=5000

## Onehot Representation:

In [13]:
message = X.copy()

In [14]:
message['description'][1]

"Organised - Focused - Vibrant - Awesome!Do you have a passion for customer service? Slick typing skills? Maybe Account Management? ...And think administration is cooler than a polar bear on a jetski? Then we need to hear you!\xa0We are the Cloud Video Production Service and opperating on a glodal level. Yeah, it's pretty cool. Serious about\xa0delivering a world class product and excellent customer service.Our rapidly expanding business is looking for a talented Project Manager to manage the successful delivery of video projects, manage client communications and drive the production process. Work with some of the coolest brands on the planet and learn from a global team that are representing NZ is a huge way!We are entering the next growth stage of our business and growing quickly internationally. \xa0Therefore, the position is bursting with opportunity for the right person entering the business at the right time.\xa090 Seconds, the worlds Cloud Video Production Service -\xa0http://90

In [15]:
message.reset_index(inplace=True)

In [16]:
import nltk
import re
from nltk.corpus import stopwords

In [19]:
# import nltk
# nltk.download()

import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [20]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['description'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [21]:
corpus[1]

'organis focus vibrant awesom passion custom servic slick type skill mayb account manag think administr cooler polar bear jetski need hear cloud video product servic opper glodal level yeah pretti cool seriou deliv world class product excel custom servic rapidli expand busi look talent project manag manag success deliveri video project manag client commun drive product process work coolest brand planet learn global team repres nz huge way enter next growth stage busi grow quickli intern therefor posit burst opportun right person enter busi right time second world cloud video product servic http url fbe afac cd c f b eef e e f ca dd second world cloud video product servic enabl brand agenc get high qualiti onlin video content shot produc anywher world fast afford manag seamlessli cloud purchas publish second remov hassl cost risk speed issu work regular video product compani manag everi aspect video project beauti onlin experi grow network rate video profession countri dedic product suc

In [22]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr[1]

[73,
 1401,
 4614,
 1647,
 43,
 1094,
 399,
 279,
 1808,
 4047,
 3053,
 2702,
 3440,
 3047,
 1901,
 1765,
 881,
 354,
 3635,
 4504,
 1321,
 3576,
 2659,
 2062,
 399,
 2548,
 806,
 1803,
 159,
 825,
 2970,
 514,
 2189,
 1272,
 2103,
 2062,
 1717,
 1094,
 399,
 1774,
 1295,
 2466,
 1625,
 1307,
 991,
 3440,
 3440,
 4556,
 3059,
 2659,
 991,
 3440,
 46,
 3184,
 203,
 2062,
 4926,
 1649,
 2756,
 1329,
 735,
 1441,
 4748,
 3840,
 3235,
 119,
 2078,
 4847,
 3658,
 3284,
 3893,
 2045,
 2466,
 3480,
 1961,
 4908,
 434,
 4896,
 844,
 4717,
 2277,
 1081,
 3658,
 2466,
 2277,
 2017,
 1906,
 1272,
 3576,
 2659,
 2062,
 399,
 2435,
 3061,
 2543,
 1984,
 2213,
 3070,
 4675,
 4077,
 4555,
 2405,
 2405,
 4675,
 2824,
 3979,
 1906,
 1272,
 3576,
 2659,
 2062,
 399,
 2756,
 1329,
 2739,
 2845,
 1503,
 4033,
 19,
 2659,
 1660,
 4902,
 4144,
 3865,
 1272,
 4107,
 4170,
 3440,
 2797,
 3576,
 932,
 438,
 1906,
 1549,
 1555,
 1706,
 2246,
 2197,
 1330,
 1649,
 2856,
 2659,
 2062,
 4693,
 3440,
 3075,
 3191,


## Embedding Representation:

In [23]:
sent_length=40
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[3385 1660 3440 ...  226  904 4140]
 [4556 3225  689 ... 1043 4333 3421]
 [   0    0    0 ... 2530 4431 3026]
 ...
 [2545 4730 4754 ... 4838  167 4629]
 [2247 4639 3447 ...  793 4908  991]
 [3032  331 1985 ... 1779 4943 3206]]


In [24]:
embedded_docs[0]

array([3385, 1660, 3440,  531, 1434, 1558, 2933, 2326,  881, 2676, 4081,
       4081,  881, 2594, 2244, 3404,  881, 1825,  881, 2142, 4919, 4627,
        150, 1702,  689, 1901, 1649, 1627, 2617,  307, 4981, 3395, 4966,
        868, 2242, 2065, 3840,  226,  904, 4140], dtype=int32)

In [25]:
embedding_vector_features=50
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(tf.keras.layers.LSTM(units = 256, return_sequences = True)),
model1.add(tf.keras.layers.Dropout(0.5)),
model1.add(tf.keras.layers.LSTM(units = 128, return_sequences = True)),
model1.add(tf.keras.layers.Dropout(0.5)),
model1.add(tf.keras.layers.LSTM(units = 64)),
model1.add(tf.keras.layers.Dense(64, activation = "relu")),
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 40, 50)            250000    
                                                                 
 lstm (LSTM)                 (None, 40, 256)           314368    
                                                                 
 dropout (Dropout)           (None, 40, 256)           0         
                                                                 
 lstm_1 (LSTM)               (None, 40, 128)           197120    
                                                                 
 dropout_1 (Dropout)         (None, 40, 128)           0         
                                                                 
 lstm_2 (LSTM)               (None, 64)                49408     
                                                                 
 dense (Dense)               (None, 64)                4

In [26]:
len(embedded_docs),y.shape

(15185, (15185,))

In [27]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [28]:
X_final[1]

array([4556, 3225,  689, 4586, 3413, 3147, 1099, 1906, 4144,   27, 2659,
       4485, 4748, 1329, 2226, 1272,    6, 2226, 2065, 2479, 4004, 4815,
       4156,  689, 2341, 3389,  739, 1702, 4627, 1993, 2341,  689,  151,
       2277, 3827, 1147, 3539, 1043, 4333, 3421], dtype=int32)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.25, random_state=32)

In [31]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
178/178 [==============================] - 80s 451ms/step - loss: 0.1820 - accuracy: 0.9561 - val_loss: 0.2171 - val_accuracy: 0.9442
Epoch 2/10
178/178 [==============================] - 79s 445ms/step - loss: 0.1817 - accuracy: 0.9561 - val_loss: 0.2158 - val_accuracy: 0.9442
Epoch 3/10
178/178 [==============================] - 80s 450ms/step - loss: 0.1814 - accuracy: 0.9561 - val_loss: 0.2179 - val_accuracy: 0.9442
Epoch 4/10
178/178 [==============================] - 98s 549ms/step - loss: 0.1811 - accuracy: 0.9561 - val_loss: 0.2172 - val_accuracy: 0.9442
Epoch 5/10
178/178 [==============================] - 94s 527ms/step - loss: 0.1681 - accuracy: 0.9561 - val_loss: 0.1956 - val_accuracy: 0.9442
Epoch 6/10
178/178 [==============================] - 88s 494ms/step - loss: 0.1341 - accuracy: 0.9617 - val_loss: 0.1852 - val_accuracy: 0.9521
Epoch 7/10
178/178 [==============================] - 82s 462ms/step - loss: 0.1083 - accuracy: 0.9678 - val_loss: 0.1741 - val_ac

## Model Performance and Accuracy:

In [33]:
y_pred=model1.predict(X_test)

119/119 [==============================] - 12s 85ms/step


We Look our dataset is Inbalance.So we use here balanced_accuracy_score

In [ ]:
from sklearn.metrics import balanced_accuracy_score
print(balanced_accuracy_score(y_test,y_pred))